from . import partner
from . import hr_employee
from . import risk_work
from . import hr_contract
from . import hr_change_reason
from . import hr_payslip
from . import hr_concept
from . import hr_payroll
from . import hr_novelty
from . import hr_loan
