{
    'name': 'Theme Epithelium',
    'summary': 'Epithelium Website',
    'version': '1.0',
    'license': '',
    'description': """ 
     
     """,
    'category': 'Theme/Creative',
    'author': "Intello Idea",
    'website': "http://www.intelloidea.com",
    'depends': ['website', 'website_theme_install', 'product', 'website_form'],
    'data': [
        'security/ir.model.access.csv',
        'data/product_category_website_data.xml',
        'data/product_form_magistral_data.xml',
        'data/product_composition_data.xml',
        #'data/product_template_data.xml',
        'data/location_city_epithelium_data.xml',
        'data/location.epithelium.csv',
        'views/website_layout.xml',
        'views/website_home.xml',
        'views/website_data.xml',
        'views/website_category.xml',
        'views/website_product.xml',
        'views/website_master_forms.xml',
        'views/website_master_form.xml',
        'views/website_info_master_form.xml',
        'views/website_products_master_form.xml',
        'views/website_purchases.xml',
        'views/product_template_view.xml',
        'views/product_category_view.xml',
        'views/product_version_view.xml',
        'views/product_composition_view.xml',
        'views/product_form_magistral_view.xml',
        'views/location_epithelium_view.xml',
        'views/manage_website_view.xml',
        'views/http_routing_template.xml',
        'views/website_thanks.xml'
    ],
    'installable': True,
    'auto_install': False,
    'application': False,
}
